sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=resource-x509-ubuntu-1404
  - INSTANCE=resource-x509-ubuntu-1604
  - INSTANCE=resource-x509-debian-7
  - INSTANCE=resource-x509-debian-8
  - INSTANCE=resource-x509-centos-6
  - INSTANCE=resource-x509-centos-7
  - INSTANCE=resource-x509-opensuse-leap
  - INSTANCE=upgrade-ubuntu-1404
  - INSTANCE=upgrade-ubuntu-1604
  - INSTANCE=upgrade-debian-7
  - INSTANCE=upgrade-debian-8
  - INSTANCE=upgrade-centos-6
  - INSTANCE=upgrade-centos-7
  - INSTANCE=upgrade-opensuse-leap
  - INSTANCE=upgrade-fedora-latest

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
