driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
- name: resource_x509
  run_list:
  - recipe[test::resource_x509]
- name: resource_dhparam
  run_list:
  - recipe[test::resource_dhparam]
- name: upgrade
  run_list:
  - recipe[test::upgrade]
- name: resource_rsa_key
  run_list:
  - recipe[test::resource_rsa_key]
